name: SPA FORMS 365
markdown: kramdown
highlighter: rouge

defaults:
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "news_item"


collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true
    
#logo: /img/logo-2x.png

gems:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
    
exclude:
  - .gitignore
  - README.md    

